[colors.primary]
background = "#0c0e10"

[font]
size = 14.0

[font.normal]
family = "Cascadia Code NF"
style = "Light"

[window]
opacity = 0.92

[window.padding]
x = 6
y = 6

[terminal.shell]
program = "tmux"
